# Generated by Django 3.0 on 2019-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('response', models.TextField()),
                ('type', models.CharField(max_length=127)),
            ],
        ),
    ]
